name: dbt CI

on:
  pull_request:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: alcm_analytics

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install dbt Fusion
        run: |
          curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update

      - name: Install dbt packages
        run: dbtf deps

      - name: Run dbt build
        run: dbtf build